# Generated by Django 2.0.9 on 2018-10-15 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_auto_20181007_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('path', models.CharField(default=manager.models.generate_path, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
