# Generated by Django 2.0.9 on 2018-10-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_vault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='label',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
