# Generated by Django 2.0.9 on 2018-10-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
