# Generated by Django 2.0.9 on 2018-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('manager', '0005_secret_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
