# Generated by Django 2.0.9 on 2018-10-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_secret_ip'),
        ('manager', '0005_auto_20181017_1438'),
    ]

    operations = [
    ]
