# Generated by Django 2.0.9 on 2018-10-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_secret_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
