# Generated by Django 2.0.9 on 2018-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_merge_20181018_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='category',
            field=models.CharField(blank=True, choices=[('DB', 'DB'), ('SERVER@LINUX', 'Linux Server'), ('SERVER@WIN', 'Windows Server'), ('GENERAL', 'General')], default='GENERAL', max_length=100, null=True),
        ),
    ]
