# Generated by Django 2.0.9 on 2018-10-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20181018_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
