# Generated by Django 2.0.9 on 2018-10-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20181018_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
