# Generated by Django 2.0.9 on 2018-10-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20181018_1128'),
        ('manager', '0008_auto_20181018_1852'),
    ]

    operations = [
    ]
