# Generated by Django 2.0.9 on 2018-10-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20181023_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
