# Generated by Django 2.0.9 on 2018-10-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge_20181018_2126'),
        ('manager', '0009_auto_20181023_1448'),
    ]

    operations = [
    ]
