# Generated by Django 2.0.9 on 2018-10-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_merge_20181023_1549'),
        ('manager', '0010_auto_20181023_1653'),
    ]

    operations = [
    ]
