version: "3"

services: 

  manager:
    image: sangah/pwd-manager:${MANAGER_VERION}
    environment: 
    - VAULT_HOST
    - VAULT_TOKEN
    - ALLOWED_HOSTS
    depends_on:
    - vault
    volumes: 
    - "web-static:/opt/pwd-manager/static"
    - "./local_settings.py:/opt/pwd-manager/pwd_manager/local_settings.py"
    - "./data/manager:/opt/pwd-manager/data"

  nginx:
    build: nginx
    ports:
    - "$MANAGER_LISTEN_PORT:80"
    volumes: 
    - "web-static:/var/www/static"

volumes: 
  web-static: