version: "3"

services: 

  manager:
    image: sangah/pwd-manager:${MANAGER_VERION}
    environment: 
    - VAULT_HOST=http://vault:8200
    - VAULT_TOKEN
    - ALLOWED_HOSTS
    depends_on:
    - vault
    volumes: 
    - "web-static:/opt/pwd-manager/static"
    - "./local_settings.py:/opt/pwd-manager/pwd_manager/local_settings.py"
    - "$MANAGER_DATA_HOME:/opt/pwd-manager/data"
    restart: "unless-stopped"

  vault:
    image: vault:${VAULT_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    environment: 
    - "VAULT_ADDR=http://0.0.0.0:8200"
    - "CONSUL_HOST=consul"
    depends_on:
    - consul
    ports:
    - "8200:8200"
    volumes: 
    - ./vault-config:/vault/config
    command: vault server -config /vault/config/config.hcl
    restart: "unless-stopped"

  consul:
    image: consul:${CONSUL_VERSION}
    volumes:
    - $VAULT_DATA_HOME:/consul/data
    command: consul agent -server -bootstrap-expect=1 -data-dir=/consul/data --client=0.0.0.0
    environment: 
    - CONSUL_BIND_INTERFACE=eth0
    restart: "unless-stopped"

  nginx:
    build: nginx
    #network_mode: "service:manager"
    ports:
    - "$MANAGER_LISTEN_PORT:80"
    depends_on: 
    - manager
    volumes: 
    - "web-static:/var/www/static"
    restart: "unless-stopped"

volumes: 
  web-static:
  vault-data: