# Generated by Django 2.0.9 on 2018-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='config2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
